# Generated by Django 5.0.3 on 2025-03-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_remove_cv_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='document_upload',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv_app.cv'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('year_started', models.PositiveIntegerField()),
                ('year_completed', models.PositiveIntegerField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='cv_app.cv')),
            ],
        ),
    ]
