# Generated by Django 5.2 on 2025-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_remove_cv_bio_remove_cv_document_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
